- id: auth-public
  match:
    url: "<{http,https}>://<**>/auth/<**>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  upstream:
    url: http://kratos:4433
    strip_path: /auth

- id: api-protected
  match:
    url: "<{http,https}>://<**>/api/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: header
  upstream:
    url: http://host.docker.internal:8080
    strip_path: /api
